name: CI

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    name: app' tests
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: automated tests
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      # scenario-2
      # frozen install of dependencies
      - run: cd scenario-2 && npm ci && npm run test

      # scenario-3
      # frozen install of dependencies
      - run: cd scenario-3 && npm ci && npm run test
